Реализация десктопной версии главной страницы
goingtogogo/airbnb-demo-frontend pull request #1
Opened 2017-11-08 23:53 UTC by goingtogogo

2017-11-09 17:32 UTC, imevro requested changes

2017-11-09 17:32 UTC, evgenyrodionov commented on public/manifest.json
> +  "short_name": "React App",
смени

2017-11-09 17:32 UTC, evgenyrodionov commented on src/Experiences/Card.js
> +          <Review>{props.review}</Review>
reviews

2017-11-09 17:32 UTC, evgenyrodionov commented on src/Experiences/Card.js
> +          <Review>{props.review}</Review>
reviews, множ число

2017-11-09 17:32 UTC, evgenyrodionov commented on src/Experiences/Styled.js
> +  margin: 8px 0px 0px 8px;
можно упростить до 8px 0

2017-11-09 17:32 UTC, evgenyrodionov commented on src/Experiences/Styled.js
> +export default function() {}
а зачем?

2017-11-09 17:32 UTC, evgenyrodionov commented on src/Experiences/index.js
> +import OpenLink from "../OpenLink";
интересный нейминг

2017-11-09 17:32 UTC, evgenyrodionov commented on src/Experiences/index.js
> +          price="69$"
числа нужно передавать числами, не строкой

2017-11-09 17:32 UTC, evgenyrodionov commented on src/Footer/index.js
> +              "Careers",
лучше декларативно

2017-11-09 17:32 UTC, evgenyrodionov commented on src/Homes/index.js
> +          review="161 Superhost"
суперхост это характеристика хозяина)

2017-11-09 17:32 UTC, evgenyrodionov commented on src/OpenLink.js
> +  return <OpenLink href="">See all</OpenLink>;
лишняя прокладка

2017-11-09 17:32 UTC, evgenyrodionov commented on src/Popular/Card.js
> +        <Pricing>{props.prising}</Pricing>
Pricing > prising

2017-11-09 17:32 UTC, evgenyrodionov commented on src/Popular/Styled.js
> +  flex-basis: 23.27235%;
ого какое магическое значение

2017-11-10 00:22 UTC, goingtogogo commented on src/Experiences/Styled.js
> +  margin: 8px 0px 0px 8px;
там очередь  верх, право, низ и лево.

2017-11-10 00:24 UTC, goingtogogo reviewed
Исправлено название проекта
Пофиксила нэйминг, передала числа числами

2017-11-10 10:07 UTC, goingtogogo commented on src/OpenLink.js
> +  return <OpenLink href="">See all</OpenLink>;
компонент же

2017-11-10 13:51 UTC, imevro requested changes

2017-11-10 13:51 UTC, evgenyrodionov commented on src/Experiences/Card.js
> +  var reviews = props.reviews + " review";
без мутабельности

2017-11-10 13:51 UTC, evgenyrodionov commented on src/Explore/Card.js
> +const Card = styled.div`
поч не ссылка

2017-11-10 13:51 UTC, evgenyrodionov commented on src/Footer/index.js
> +    "Careers",
а сами ссылки ты передать не хочешь?

и вообще, зачем это программирование массивами? `<Link href="/careers">Careers</Link>` удобнее, чем вот это

2017-11-10 13:51 UTC, evgenyrodionov commented on src/SeeAll.js
> +  return <SeeAll href="">See all</SeeAll>;
зачем этот компонент-прокладка?

2017-11-11 01:18 UTC, goingtogogo commented
Здесь десктоп, таблетка и мобайл

2017-11-11 11:23 UTC, evgenyrodionov commented on src/Experiences/Styled.js
> +  margin: 8px 0px 0px 8px;
а

2017-11-11 11:31 UTC, imevro requested changes

2017-11-11 11:31 UTC, evgenyrodionov commented on src/Experiences/Styled.js
> +  @media (max-width: 576px) {
читай 7 урок про адаптивность, max-width хуже чем min-width

2017-11-11 11:31 UTC, evgenyrodionov commented on src/Explore/Card.js
> +const Card = styled.div`
?

2017-11-11 11:31 UTC, evgenyrodionov commented on src/Footer/Styled.js
> +    width: 96%;
зачем? почему? есть же .container в фбг

2017-11-11 11:31 UTC, evgenyrodionov commented on src/Footer/Styled.js
>    -moz-appearance: none;
можно опустить — в СК есть автопрефиксер

2017-11-11 11:31 UTC, evgenyrodionov commented on src/Header/Styled.js
> +    right: 87%;
если такой большой right, не проще ли использовать left?

2017-11-11 11:31 UTC, evgenyrodionov commented on src/Styled.js
> +    overflow-y: hidden;
а зачем?

2017-11-11 11:31 UTC, evgenyrodionov commented on src/Styled.js
> +  &: after {
опечатка

2017-11-11 21:05 UTC, goingtogogo commented on src/Explore/Card.js
> +const Card = styled.div`
коротнуло чет

2017-11-12 11:24 UTC, imevro approved these changes

2017-11-12 11:25 UTC, merged

2017-11-12 11:25 UTC, evgenyrodionov commented
Сделай гит пулл в мастере