Реализация планшетной версии главной страницы
goingtogogo/airbnb-demo-frontend pull request #2
Opened 2017-11-10 00:27 UTC by goingtogogo

2017-11-10 15:38 UTC, evgenyrodionov commented
Не вешай коммиты после запроса ревью

2017-11-10 15:39 UTC, evgenyrodionov commented
ПР нужно направлять в тот бранч, от которого делала этот

2017-11-10 15:42 UTC, imevro requested changes

2017-11-10 15:42 UTC, evgenyrodionov commented on src/Experiences/Styled.js
> +    flex-basis: 31.91489%;
жесть конечно, мб округлять будешь?

2017-11-10 15:42 UTC, evgenyrodionov commented on src/Footer/Bottom.js
> +const Instagram = styled.img`
а поч ты просто не можешь сделать один компонент Icon какой-нибудь?

2017-11-10 15:42 UTC, evgenyrodionov commented on src/Header/Styled.js
> +export const Logo = styled.img`margin-top: 6px}`;
синтаксис сломан

2017-11-10 15:42 UTC, evgenyrodionov commented on src/Homes/Styled.js
> +    align-celf: flex-start;
celf?

2017-11-10 15:42 UTC, evgenyrodionov commented on src/Styled.js
> +    -ms-overflow-style: -ms-autohiding-scrollbar;
не надо этого делать

2017-11-11 00:53 UTC, merged

2017-11-11 01:15 UTC, goingtogogo commented
Изменения отправлены в develop