Home filters
goingtogogo/airbnb-demo-frontend pull request #5
Opened 2017-11-24 01:37 UTC by goingtogogo

Что реализовано: десктопные фильтры, логика открытия, закрытия с сохранением стейта и сбросом

2017-11-24 01:37 UTC, goingtogogo commented
https://build-kvvohdepdl.now.sh/homes

2017-11-24 15:14 UTC, evgenyrodionov commented
Попидорасило знатно
![image](https://user-images.githubusercontent.com/775692/33216040-3de9fd82-d143-11e7-908d-8ab1e7d95caa.png)

2017-11-24 15:15 UTC, evgenyrodionov commented
Плюс тут не показываются выбранные значения в кнопке 
![image](https://user-images.githubusercontent.com/775692/33216066-5a0b8ddc-d143-11e7-94f9-c3b1279a8cff.png)

2017-11-24 15:31 UTC, imevro requested changes

2017-11-24 15:31 UTC, evgenyrodionov commented on src/Homes/Filters/Filter.js
> +          toCancel={this.handleCancelClick}
обычно хэндлеры называют `on*` вместо `to*`

2017-11-24 15:31 UTC, evgenyrodionov commented on src/Homes/Filters/Guests.js
> +        Object.assign([], this.props.guests, {
а зачем обджект ассайн? spread оператор работает и в массивах

2017-11-24 15:31 UTC, evgenyrodionov commented on src/Homes/Filters/MoreFilters.js
> +  onSwitch = switcher => {
ставь переносы между методами

2017-11-24 15:31 UTC, evgenyrodionov commented on src/Homes/Filters/MoreFilters.js
> +    if ([...this.props.amenities].filter(x => x === amenity).length > 0) {
а зачем тут копировать через спредоператор?

2017-11-24 15:31 UTC, evgenyrodionov commented on src/Homes/Filters/MoreFilters.js
> +              onClick={() => this.handleFacilities("elebator")}
елебатор 
![you need to login to view this link _e69c9b0ab55b1263dc62d9f65114850f](https://user-images.githubusercontent.com/775692/33216476-0f992a14-d145-11e7-8eda-00ae5cf5c2d9.png)

2017-11-24 15:31 UTC, evgenyrodionov commented on src/Homes/Filters/RoomType.js
> +            isChecked={this.props.rooms.includes("privat") && this.props.isOpen}
private?

2017-11-24 15:31 UTC, evgenyrodionov commented on src/Homes/Filters/index.js
> +  handleCancel = title => {
а теперь попробуй это всё поупрощать

2017-11-24 19:55 UTC, goingtogogo commented
https://build-nlakevpdjw.now.sh

2017-11-24 21:06 UTC, evgenyrodionov commented
Сделай при ховере курсор поинтер
![image](https://user-images.githubusercontent.com/775692/33223778-0a89d4fe-d174-11e7-8303-ee877c494a1f.png)

Ну а тут-то чё не обновляется лейбл)
![image](https://user-images.githubusercontent.com/775692/33223810-56517842-d174-11e7-9271-265ce1841017.png)

Там какой-то оч долгий ререндер, сделай так чтобы этого не было видно
![image](https://user-images.githubusercontent.com/775692/33223816-61423b56-d174-11e7-85a8-16ce6ecf329a.png)

Сделай весь блок кликабельным, а не только чекбокс
![image](https://user-images.githubusercontent.com/775692/33223825-71d69b88-d174-11e7-816b-a887a5db1311.png)

2017-11-24 23:07 UTC, imevro requested changes

2017-11-24 23:07 UTC, evgenyrodionov commented on src/Homes/Filters/Dates.js
> +      dates: { startDate: startDate, endDate: endDate }
используй object shorthand

2017-11-24 23:07 UTC, evgenyrodionov commented on src/Homes/Filters/Guests.js
> +        guests: Object.values({
а зачем тебе object.values?

2017-11-24 23:07 UTC, evgenyrodionov commented on src/Homes/Filters/index.js
> +    guests: [1, 0, 0], // {aud: 0, pizduki: 0}
??????????????????

2017-11-24 23:07 UTC, evgenyrodionov commented on src/Homes/Filters/index.js
> +    if (title === "Price") this.onChange({ prices: { min: 10, max: 1000 } });
намного лучше, но ты можешь ещё проще — вынести эти проверки внутрь компонентов и вызывать оттуда `onChange`

2017-11-24 23:07 UTC, evgenyrodionov commented on src/Homes/Room/Overview.js
> +        <Properties>
засунь в массив сразу и итерируйся по нему

2017-11-25 00:46 UTC, goingtogogo commented on src/Homes/Filters/index.js
> +    guests: [1, 0, 0], // {aud: 0, pizduki: 0}
да, сорян  там {aud: 0, lichinousy: 0}

2017-11-28 00:17 UTC, goingtogogo commented
https://build-jovloofsbt.now.sh

2017-11-28 07:36 UTC, evgenyrodionov commented
Смотри: если я щас нажму таб, я перейду сразу на Cancel. А как мне перейти на чекбоксы и выбрать что-то там? 

![image](https://user-images.githubusercontent.com/775692/33307542-ebd13384-d427-11e7-87f8-5091ce95e01a.png)

2017-11-28 20:17 UTC, imevro requested changes

2017-11-28 20:17 UTC, imevro commented on src/App.js
> +import Homes from "./Homes/All";
а зачем олл? был же индекс норм

2017-11-28 20:17 UTC, imevro commented on src/App.js
> +import Homes from "./Homes/All";
ну или List

2017-11-28 20:17 UTC, imevro commented on src/Homes/All/Content.js
> +      {cards.map((item, index) => (
хуитем)))

2017-11-28 20:17 UTC, imevro commented on src/Homes/All/Filters/Guests.js
> +      guests: {
если ты в гуестс, есть ли нужда еще одно поле делать? ты же можешь делать просто `this.props.onGuestsChange({ ...this.props.values, [type]: +1 })`

А в идеале вообще отдавать чистые данные — зацени как проще станет родитель, если у него будет `onChange(key, value)`. А ключ (`guests`) уже передавать отсюда

2017-11-28 20:17 UTC, imevro commented on src/Homes/All/Filters/Guests.js
> +      guests: [1, 0, 0]
а откуда массив взялся?

2017-11-28 20:17 UTC, imevro commented on src/Homes/All/Filters/Guests.js
> +    this.props.onClose("Guests");
мб лучше передавать как type?

2017-11-28 20:17 UTC, imevro commented on src/Homes/All/Filters/MoreFilters.js
> +        beds: Object.values({
храни ключом

2017-11-28 20:17 UTC, imevro commented on src/Homes/All/Filters/MoreFilters.js
> +        beds: Object.values({
то есть объектом

2017-11-28 20:17 UTC, imevro commented on src/Homes/All/Filters/MoreFilters.js
> +          {/* <Impovements onClick={() => this.handleFacilities("elevator")}>
вынеси мусор

2017-11-28 20:17 UTC, evgenyrodionov commented on src/Homes/Room/Reviews/Review.js
> +          <Date>{props.date}</Date>
резервное слово в джсе

2017-11-28 20:17 UTC, evgenyrodionov commented on src/Homes/Room/Reviews/index.js
> +        <Option>
вынеси в отдельный компонент?

2017-11-28 20:17 UTC, evgenyrodionov commented on src/Landing/Homes/index.js
> +import Card from "../../Homes/All/Card";
а зачем в олл класть? поч не в корне Homes?

2017-11-29 19:46 UTC, goingtogogo commented
https://build-ufuvlxrunk.now.sh

2017-11-29 19:52 UTC, goingtogogo commented
rooms десктоп

2017-11-29 20:34 UTC, goingtogogo commented
https://build-baxpmxmiyo.now.sh

2017-11-29 20:34 UTC, goingtogogo commented
rooms десктоп

2017-11-30 07:37 UTC, evgenyrodionov commented
бля а зачем здесь румс десктоп? Тут про фильтры всё!

2017-11-30 07:39 UTC, evgenyrodionov commented
Не работает таб 
![image](https://user-images.githubusercontent.com/775692/33419209-86a16c24-d5ba-11e7-8729-bd691e507adf.png)

Используй атрибут `disabled` чтобы нельзя было переключаться на выключенные кнопки
![image](https://user-images.githubusercontent.com/775692/33419226-945ed8b0-d5ba-11e7-9155-0cefbec922ae.png)

Почему-то при фокусе на элемент и нажатии на пробел скроллится страница

Как-то колхозно, почему не только чекбоксы?
![image](https://user-images.githubusercontent.com/775692/33419252-aa598e3a-d5ba-11e7-86e6-18e74c772c9e.png)

![image](https://user-images.githubusercontent.com/775692/33419259-b1c53462-d5ba-11e7-9d32-923e8d0f96e4.png)

2017-11-30 08:07 UTC, imevro approved these changes

2017-11-30 08:07 UTC, evgenyrodionov commented
Пофикси поведение (и не через onKeyPress и tabIndex)

2017-12-01 21:03 UTC, goingtogogo commented
https://build-kvockzzihk.now.sh

2017-12-02 14:56 UTC, evgenyrodionov commented
Уехало
![image](https://user-images.githubusercontent.com/775692/33516794-cd03e1b2-d789-11e7-92fb-3ef875cefbb2.png)

Аутлайн нет при фокусе на кнопке переключения
![image](https://user-images.githubusercontent.com/775692/33516800-dded5cf6-d789-11e7-8683-c10105de09eb.png)

Плюс не работает, а на минус почему-то переключиться могу, хотя он должен быть дизейблед
![image](https://user-images.githubusercontent.com/775692/33516810-fc0cc0a0-d789-11e7-9240-0aeaf4053141.png)

Не могу на эту кнопку переключиться табом
![image](https://user-images.githubusercontent.com/775692/33516813-05a443c2-d78a-11e7-9d47-9b06346bb92f.png)

Кнопки сожрало
![image](https://user-images.githubusercontent.com/775692/33516814-0ef466d2-d78a-11e7-8970-ef590ff6f2e0.png)

2017-12-02 14:56 UTC, evgenyrodionov commented
Румс выкидывай отсюда в отдельный ПР, не буду проверять

2017-12-02 18:26 UTC, goingtogogo commented
https://build-caxbmzyzaa.now.sh

2017-12-02 20:44 UTC, goingtogogo commented
![image](https://user-images.githubusercontent.com/17799611/33519589-b49089ba-d7ba-11e7-8fb7-ff2c1a654e15.png)

2017-12-07 23:11 UTC, evgenyrodionov commented
Напиши в чат, утром разберемся — я запутался в твоих ПРах

2018-02-01 15:59 UTC, merged